# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
target 'PYAFN' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PYAFN

  target 'PYAFNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PYAFNUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
